---
- name: Install Elasticsearch
  hosts: localhost
  become: yes
  vars_files:
    - ./vars/index.yaml

  tasks:
    - name: Ensure wget is installed
      apt:
        name: wget
        state: present

    - name: Download and add Elasticsearch GPG key
      ansible.builtin.shell: |
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
      args:
        creates: /usr/share/keyrings/elasticsearch-keyring.gpg

    - name: Ensure apt-transport-https is installed
      apt:
        name: apt-transport-https
        state: present

    - name: Add Elasticsearch APT repository
      ansible.builtin.shell: |
        echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-8.x.list
      args:
        creates: /etc/apt/sources.list.d/elastic-8.x.list

    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Install Kibana
      apt:
        name: kibana
        state: present

    - name: Getting hostname
      command: hostname
      register: hostname
      ignore_errors: yes

    - name: Install configuration file for elasticsearch
      template:
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        mode: 0755
        force: yes

    - name: Install configuration file for kibana
      template:
        src: kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        mode: 0755
        force: yes

    - name: Reload systemd manager configuration
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable Elasticsearch service
      ansible.builtin.systemd:
        name: elasticsearch
        enabled: yes

    - name: Start Elasticsearch service
      ansible.builtin.systemd:
        name: elasticsearch
        state: started

    - name: Enable Kibana service
      ansible.builtin.systemd:
        name: kibana
        enabled: yes

    - name: Start Kibana service
      ansible.builtin.systemd:
        name: kibana
        state: started

    - name: Setting Elasticsearch password using elasticsearch-reset-password script
      shell: |
        echo "{{ es_password }}\n{{ es_password }}\n" | /usr/share/elasticsearch/bin/elasticsearch-reset-password -u {{ es_user }} -b -i -f -s
      register: reset_result
      failed_when: "'ERROR' in reset_result.stderr"
      ignore_errors: no

    - name: Setting Kibana password using elasticsearch-reset-password script
      shell: |
        echo "{{ kb_password }}\n{{ kb_password }}\n" | /usr/share/elasticsearch/bin/elasticsearch-reset-password -u {{ kb_user }} -b -i -f -s
      register: reset_result
      failed_when: "'ERROR' in reset_result.stderr"
      ignore_errors: no