version: '3'

services:

  fhir:
    container_name: fhir
    image: hapiproject/hapi:v5.7.0
    ports:
      - "8080:8080"
    environment:
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://db:5432/hapi'
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.search.enabled: 'true'
      spring.jpa.properties.hibernate.search.backend.type: lucene
      spring.jpa.properties.hibernate.search.backend.analysis.configurer: ca.uhn.fhir.jpa.search.HapiLuceneAnalysisConfigurer
      spring.jpa.properties.hibernate.search.backend.directory.type: local-filesystem
      spring.jpa.properties.hibernate.search.backend.directory.root: target/lucenefiles
      spring.jpa.properties.hibernate.search.backend.lucene_version: lucene_current
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hapi.fhir.tester.home.server_address: "http://localhost:8080/fhir"
      hapi.fhir.enable_index_missing_fields: 'true'

    volumes:
      - hapi-data:/data/hapi
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5432:5432"

volumes:
    hapi-data:
        # external: true