version: '3'

services:

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

  ihris:
    container_name: ihris
    image: ihris/ihris
    ports:
      - "3000:3000"
    depends_on:
      - redis
    #  - fhir
    # - es
    restart: on-failure
    environment:
      IHRIS_FHIR__BASE: http://fhir:8080/fhir
      AUTOLOAD_RESOURCE_DIR: ../resources
      IHRIS_REDIS__URL: http://redis


volumes:
  redis-data: