name: docker

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ihris-backend/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: |
            ihris/ihris:${{ github.sha }}
            # wont work apparently
            # ihris/ihris:$(git rev-parse --short HEAD)
            ihris:latest
        #   build-args: |
        #     arg1=value1
        #     arg2=value2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
